-- MySQL Script generated by MySQL Workbench
-- Wed Apr 30 11:32:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PizzaClub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PizzaClub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PizzaClub` DEFAULT CHARACTER SET utf8 ;
USE `PizzaClub` ;

-- -----------------------------------------------------
-- Table `PizzaClub`.`Vecinity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzaClub`.`Vecinity` (
  `idVecinity` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(60) NOT NULL,
  `Province` INT NOT NULL,
  `PostalCode` INT(7) NOT NULL,
  PRIMARY KEY (`idVecinity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PizzaClub`.`Province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzaClub`.`Province` (
  `idProvince` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(60) NOT NULL,
  `Vecinities` INT NULL,
  PRIMARY KEY (`idProvince`),
  INDEX `Vecinities_idx` (`Vecinities` ASC) VISIBLE,
  CONSTRAINT `Vecinities`
    FOREIGN KEY (`Vecinities`)
    REFERENCES `PizzaClub`.`Vecinity` (`idVecinity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PizzaClub`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzaClub`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Adress` VARCHAR(60) NOT NULL,
  `Postal_Code` INT NOT NULL,
  `Province` INT NOT NULL,
  `Telephone` VARCHAR(15) NOT NULL,
  `Vecinity` INT NOT NULL,
  PRIMARY KEY (`idClient`),
  INDEX `Vecinity_idx` (`Vecinity` ASC) VISIBLE,
  CONSTRAINT `Vecinity`
    FOREIGN KEY (`Vecinity`)
    REFERENCES `PizzaClub`.`Vecinity` (`idVecinity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PizzaClub`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzaClub`.`Store` (
  `idStore` INT NOT NULL AUTO_INCREMENT,
  `Adress` TEXT NOT NULL,
  `PostalCode` INT NOT NULL,
  `Province` INT NOT NULL,
  `Vecinity` INT NOT NULL,
  PRIMARY KEY (`idStore`),
  INDEX `Vecinity_idx` (`Vecinity` ASC) VISIBLE,
  CONSTRAINT `Vecinity`
    FOREIGN KEY (`Vecinity`)
    REFERENCES `PizzaClub`.`Vecinity` (`idVecinity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PizzaClub`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzaClub`.`Employees` (
  `idEmployees` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(60) NOT NULL,
  `LastName` VARCHAR(60) NOT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  `Telephone` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `Store` INT NOT NULL,
  PRIMARY KEY (`idEmployees`),
  INDEX `Store_idx` (`Store` ASC) VISIBLE,
  CONSTRAINT `Store`
    FOREIGN KEY (`Store`)
    REFERENCES `PizzaClub`.`Store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PizzaClub`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzaClub`.`Order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `ClientID` INT NOT NULL,
  `StoreID` INT NOT NULL,
  `idEmployee` INT NOT NULL,
  `Date_Time` DATETIME NOT NULL,
  `PickUp_or_Delivery` CHAR(1) NOT NULL,
  `Total_Price` DECIMAL NOT NULL,
  `Produce_Amount` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `Client_idx` (`ClientID` ASC) VISIBLE,
  INDEX `Store_idx` (`StoreID` ASC) VISIBLE,
  INDEX `Delivery_Person_idx` (`idEmployee` ASC) VISIBLE,
  CONSTRAINT `Client`
    FOREIGN KEY (`ClientID`)
    REFERENCES `PizzaClub`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Store`
    FOREIGN KEY (`StoreID`)
    REFERENCES `PizzaClub`.`Store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Delivery_Person`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `PizzaClub`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PizzaClub`.`Cathegory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzaClub`.`Cathegory` (
  `idCathegory` INT NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCathegory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PizzaClub`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzaClub`.`Product` (
  `idProduct` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Type` CHAR(1) NOT NULL,
  `Description` TEXT(150) NOT NULL,
  `Photo` BLOB NOT NULL,
  `Price` FLOAT NOT NULL,
  `Category` INT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `Cathegory_idx` (`Category` ASC) VISIBLE,
  CONSTRAINT `Cathegory`
    FOREIGN KEY (`Category`)
    REFERENCES `PizzaClub`.`Cathegory` (`idCathegory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PizzaClub`.`Order_Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzaClub`.`Order_Details` (
  `idOrder` INT NOT NULL,
  `Products` JSON NOT NULL,
  INDEX `OrderID_idx` (`idOrder` ASC) VISIBLE,
  INDEX `Products_idx` (`Products` ASC) VISIBLE,
  PRIMARY KEY (`idOrder`),
  CONSTRAINT `OrderID`
    FOREIGN KEY (`idOrder`)
    REFERENCES `PizzaClub`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Products`
    FOREIGN KEY (`Products`)
    REFERENCES `PizzaClub`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PizzaClub`.`Order_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzaClub`.`Order_Product` (
  `idOrder` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `Quantity` INT NOT NULL,
  PRIMARY KEY (`idOrder`, `idProduct`),
  INDEX `FK_OrderProduct_Product` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `FK_OrderProduct_Order`
    FOREIGN KEY (`idOrder`)
    REFERENCES `PizzaClub`.`Order` (`idOrder`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_OrderProduct_Product`
    FOREIGN KEY (`idProduct`)
    REFERENCES `PizzaClub`.`Product` (`idProduct`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
