-- MySQL Script generated by MySQL Workbench
-- Wed Apr 30 11:14:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8mb3 ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`providers` (
  `idProviders` INT NOT NULL AUTO_INCREMENT,
  `Provider_Name` VARCHAR(60) NOT NULL,
  `Adress` TEXT NOT NULL,
  `Postal_Code` INT NOT NULL,
  `Telephone` VARCHAR(45) NOT NULL,
  `Fax` VARCHAR(45) NULL DEFAULT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProviders`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optica`.`Label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Label` (
  `idLabel` INT NOT NULL AUTO_INCREMENT,
  `FrameName` VARCHAR(45) NOT NULL,
  `Provider` INT NULL,
  PRIMARY KEY (`idLabel`),
  INDEX `Provider_idx` (`Provider` ASC) VISIBLE,
  CONSTRAINT `Provider`
    FOREIGN KEY (`Provider`)
    REFERENCES `optica`.`providers` (`idProviders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`clients` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `Client_Name` VARCHAR(70) NOT NULL,
  `Postal_Code` INT NULL DEFAULT NULL,
  `Email` VARCHAR(70) NOT NULL,
  `Phone_number` VARCHAR(20) NULL DEFAULT NULL,
  `Register_Date` DATE NULL DEFAULT NULL,
  `Refered_By` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optica`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`employees` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(70) NOT NULL,
  `Sales` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idEmployee`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optica`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`providers` (
  `idProviders` INT NOT NULL AUTO_INCREMENT,
  `Provider_Name` VARCHAR(60) NOT NULL,
  `Adress` TEXT NOT NULL,
  `Postal_Code` INT NOT NULL,
  `Telephone` VARCHAR(45) NOT NULL,
  `Fax` VARCHAR(45) NULL DEFAULT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProviders`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optica`.`frames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`frames` (
  `idFrames` INT NOT NULL AUTO_INCREMENT,
  `Label` VARCHAR(45) NULL DEFAULT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Prescription_Left` DECIMAL(4,0) NULL DEFAULT NULL,
  `Prescription_Rigth` DECIMAL(4,0) NULL DEFAULT NULL,
  `FrameColor` VARCHAR(45) NOT NULL,
  `LensColor` VARCHAR(45) NULL DEFAULT NULL,
  `Price` FLOAT NOT NULL,
  `Provider` INT NOT NULL,
  PRIMARY KEY (`idFrames`),
  INDEX `Providers_idx` (`Provider` ASC) VISIBLE,
  CONSTRAINT `Providers`
    FOREIGN KEY (`Provider`)
    REFERENCES `optica`.`providers` (`idProviders`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optica`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`sales` (
  `SaleId` INT NOT NULL AUTO_INCREMENT,
  `Seller` INT NOT NULL,
  `Client` INT NULL DEFAULT NULL,
  `Frame` INT NULL DEFAULT NULL,
  `Sale_Date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`SaleId`),
  INDEX `Client_idx` (`Client` ASC) VISIBLE,
  INDEX `Seller_idx` (`Seller` ASC) VISIBLE,
  INDEX `Frame_idx` (`Frame` ASC) VISIBLE,
  CONSTRAINT `Client`
    FOREIGN KEY (`Client`)
    REFERENCES `optica`.`clients` (`idClient`),
  CONSTRAINT `Frame`
    FOREIGN KEY (`Frame`)
    REFERENCES `optica`.`frames` (`idFrames`),
  CONSTRAINT `Seller`
    FOREIGN KEY (`Seller`)
    REFERENCES `optica`.`employees` (`idEmployee`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
